dowjones/react-dropdown-tree-select

package.json
Should help prevent apps consuming this component from loading multiple version of React.
#19
=> remove react as dependency and add as dev dependency

README.md, src/index.css, src/index.js, src/tree-manager/index.js, src/tree-node/index.css, src/tree-node/index.js, src/tree-node/index.test.js, src/tree/index.js
feat: remove cascading `!important` in css for hidden nodes (it's repaced by JS conditional style  and allow to  override this behaviour easily)
feat: add a "keepTreeOnSearch" prop to display results as a tree instead of flattening them (parent that don't match but with children which match are displayed with a specific class (ATM, it reduces opacity too))
=> Improvement: remove usage of !important to remove the padding of nodes during  search

src/index.js
When using simpleSelect, and having multiple instances of the component on the same page, opening
dropdown content after selecting something in another dropdwon causes the previous dropdown to open
as well. This happens since  `handleOutsideClick` is still listening for changes on the previous
instance.
=> fix: Unregister event listener for simpleSelect :bug:

types/react-dropdown-tree-select.d.ts
An issue in #223 for children. An array of Node[] instead of TreeNode[] was specified.
=> fix: Typing error for children

src/tree-node/index.test.js, src/tree-node/toggle.js
Prevents event bubbling on node expand-click. The function isOutsideClick only gets a short part of two items (li.node + i.expand), then the parents stop, in Firefox. This causes it to be detected as an outside click.
In chrome the path is instead empty and no outside click is therefore detected.
Fixes #198 
Can test here (switching between v1.17/developTemp):
Expand the first two nodes:
Scroll to bottom and expand:
https://ellinge.github.io/react-dropdown-tree-select-test/#v117-nocheckeddefault
https://ellinge.github.io/react-dropdown-tree-select-test/#DevelopTemp-nocheckeddefault
There still seems to be some issue with scroll in firefox after initial scroll and expand which does not happen in chrome. The expanded item gets out of view. This also happens on scoll and check.
=> fix: Prevent dropdown close on expand in Firefox

README.md
Adds a "types (friendly) badge" to Readme
=> docs: Add types friendly badge 📚

.babelrc, package.json, webpack.config.js, yarn.lock
Removes `babel-runtime` from the distribution bundle, reducing the size of the component.  `babel-runtime` is only needed for tests.
=> fix: Remove babel-runtime from distribution bundle (#248) 🔥

README.md, docs/src/stories/Options/index.js, package.json, src/index.js, src/tree-manager/index.js, src/tree-node/index.js, src/tree-node/node-label.js, src/tree/index.js, src/trigger/index.js, types/react-dropdown-tree-select.d.ts
BREAKING: hierarchical prop
`hierarchical` prop is now moved under `mode` prop.
```
// before
<DropdownTreeSelect data={data} hierarchical={true} />
// after
<DropdownTreeSelect data={data} mode="hierarchical" />
```
=> refactor: Update mode to include hierarchical

README.md
Fixes the quick link for readme to lower case according to @mrchief suggestion making it possible to release without #272
=> fix: Adjust quicklink for search predicate

.vscode/launch.json, src/tree-manager/index.js, src/tree-manager/tests/index.test.js
Ancestor nodes, that contained match term, were always marked hidden or translucent if a child node contained the match term. This PR fixes that issue.
Fixes #291 
=> fix: Do not hide ancestor nodes if they match 🐛

.gitignore, package.json, src/index.js, src/input/index.js, src/tag/index.js, src/tree-node/index.js, src/tree-node/node-label.js, src/tree-node/toggle.js, src/trigger/index.js, yarn.lock
Gets rid of classnames dependency. This package was not being used for its main features anyway (just for emitting classnames conditionally). 
=> feat: Reduce bundle size by removing classnames

src/index.js
Guards against accessing null ref with inline search input.
Fixes #335 
=> fix: Guard against accessing null ref with inline search input

src/index.js, src/index.test.js, src/tree-manager/keyboardNavigation.js
We keep track of current focus on keyboard navigation but we don't update it on mouse clicks (checkbox toggle).
Fixes #329.
=> fix: Change focus on mouse/checkbox toggle also #329

src/tree-manager/keyboardNavigation.js, src/tree/index.js
resolved findIndex() method issue can't support on internet explorer,
findIndex method can't support on IE browser #347
=> fix: IE11 doesn't support Array.findIndex

src/tree-manager/index.js, src/tree-manager/tests/partialSelect.test.js
Clears the partial status from the parents of the previous node, when using radioSelect.
Fixes #372
=> fix: Clear partial status of previous radio select parents

README.md, src/index.js, src/index.test.js
When using controlled data, if the data changes the focused node will be the latest one (the one before, first one is "null").
Take the latest state moving the get Focused functionality inside the setState, this ensure to use the latest one.
=> fix: Delayed focused update when receiving data changes

package-lock.json, src/tree-node/index.js, src/tree-node/toggle.js
Fixed padding (indentation) of leaf nodes for all levels
=> fix: Padding of leaf nodes for all levels

.github/workflows/ci.yml
This makes `yarn test` run on PullRequests.
I think it is good, and as I saw that somehow `coveralls` cannot run, it would be good to have tests run at least.
=> fix: Make tests run in actions

types/react-dropdown-tree-select.d.ts
Adds a missing prop in TextProps interface inside 'react-dropdown-tree-select.d.ts' according to the docs.
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] Updated documentation (if applicable)
- [    ] Added tests that prove my fix is effective or that my feature works
- [ x ] New and existing unit tests pass locally with my changes
- [ x ] My changes generate no new warnings
This is a previous pull request with verified commits
=> fix: Added missing prop 'inlineSearchPlaceholder' in 'TextProps' interface

README.md, package.json
With NPM 7 peer dependencies are automatically installed unlike previous versions. Since React 17
was not defined as a peer dependency hence the install of package failed on projects using Npm7 + React
17.
React 17 support #486
This fixes the install error that occurred when working with NPM 7 and React 17 by adding react 17 to peer dependencies.
Before 
After
Fixes #486 
=> fix(install): Adding react 17 to peer dependencies

src/tree/index.js
See issue #472 and discussion #479 for details and context. 
Only moved the "shouldRenderNode" method within the Tree component and changed its argument a bit to solve a compilation problem. I actually didn't get why that method was outside of the component... any reasons for that? 
I put it in the component because I thought this might solve the compilation problem I faced (along with the argument change). 
I needed this fix to properly compile this lib with react-scripts. I don't know why the bug I found actually happens, if it is something in the original code or the way react-scripts minify that lib dist files... but the fix I did actually solve my problem so... 
I didn't actually add any new unit tests... I'm not even sure how I could do a proper test for that bug as it only happens …
=> fix(compilation): Fixing the searchModeOn compilation problem

package.json, src/index.js, src/tree/index.js, yarn.lock
Adds support for React 18, which ends support for certain lifecycle methods not prefixed by unsafe_.
See: https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html
For additional context
Fixes #560
=> feat: Minimum react 18 support

src/index.js
When you have tens of thousands of items in a search tree, and you type search input, the cost can be extremely high when you have zero or one characters, especially when you are using a custom search predicate. There is no need to incur the cost of filtering the tree if the text input is zero length. Instead, just reset the search state.
I'll note here that the example in the demo that is supposed to test [a large-scale scenario](https://dowjones.github.io/react-dropdown-tree-select/#/story/large-tree) doesn't appear to be all that taxing because the number of nested nodes is very low. You need a lot of nested nodes to encounter performance issues. In my testing, I have almost 100k nodes at up to 10 levels of nesting. I also have `keepTreeOnSearch` on which probably exacerbates the …
=> feat: Do not incur cost of filtering tree if search mode is off
